/**
 * Migration 386: backfill `slots` (armor) and `skill`/`damage`/`delay`
 * (weapons) on Blacksmithing's existing produced items.
 *
 * decisions/item-node-schema.md's stat block already has these fields, but
 * every Blacksmithing migration to date (#48, #65) sourced its item data
 * from eqlwiki's recipe/component tables, which don't carry an item's own
 * Slot/Skill line -- that only lives on the item's own individual eqlwiki
 * page. 313 of Blacksmithing's 323 produced items had neither field set.
 *
 * Backfilled by batch-fetching every one of those 313 items' own eqlwiki
 * pages via the raw wikitext API (action=query&prop=revisions, 40 titles
 * per request -- same batched-multi-title technique as Brewing's ingredient
 * data, decisions/tradeskill-recipe-node-schema.md), parsing each page's
 * `{{Itempage}}` statsblock's `Slot:`/`Skill:`/`DMG:`/`Atk Delay:` lines
 * directly -- no WebFetch summarization, no inferring slot from item-name
 * patterns. All 313 pages existed; 37 (raw ore/sheet-metal/tool/container
 * intermediates -- File, Skewers, Pot, Smoker, etc.) genuinely have neither
 * field on their own page and are left untouched, same as any other
 * "absence is the real fact" case in this graph.
 *
 * One real oddity worth recording rather than silently smoothing over:
 * eqlwiki's own infobox literally reads `Skill: Throwingv2` (not "Throwing")
 * for every throwing weapon (Forged Javelin/Shuriken/Throwing Axe/Throwing
 * Knife and their Velium counterparts, Antonian Javelin) -- consistent
 * across all of them, so kept verbatim rather than assumed to be a typo.
 */

import { loadGraph } from "./_lib";

const { updateNode, save } = loadGraph(import.meta.dir);

interface Update {
  id: string;
  slots?: string[];
  skill?: string;
  delay?: number;
  damage?: number;
}

const updates: Update[] = [
  { id: "item:banded-mask", slots: ["Face"] },
  { id: "item:banded-gorget", slots: ["Neck"] },
  { id: "item:banded-bracer", slots: ["Wrist"] },
  { id: "item:banded-boots", slots: ["Feet"] },
  { id: "item:banded-belt", slots: ["Waist"] },
  { id: "item:banded-mantle", slots: ["Shoulders"] },
  { id: "item:banded-cloak", slots: ["Back"] },
  { id: "item:banded-gauntlets", slots: ["Hands"] },
  { id: "item:banded-sleeves", slots: ["Arms"] },
  { id: "item:banded-helm", slots: ["Head"] },
  { id: "item:banded-leggings", slots: ["Legs"] },
  { id: "item:banded-mail", slots: ["Chest"] },
  { id: "item:skinning-knife", slots: ["Primary", "Secondary"], skill: "Piercing", delay: 25, damage: 2 },
  { id: "item:antonian-javelin", slots: ["Range", "Ammo"], skill: "Throwingv2", delay: 30, damage: 8 },
  { id: "item:forged-bastard-sword", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 33, damage: 7 },
  { id: "item:forged-battle-axe", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 34, damage: 7 },
  { id: "item:forged-dagger", slots: ["Primary", "Secondary"], skill: "Piercing", delay: 21, damage: 3 },
  { id: "item:forged-halberd", slots: ["Primary"], skill: "2H Slashing", delay: 48, damage: 14 },
  { id: "item:forged-long-sword", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 28, damage: 6 },
  { id: "item:forged-mace", slots: ["Primary", "Secondary"], skill: "1H Blunt", delay: 36, damage: 7 },
  { id: "item:forged-morning-star", slots: ["Primary", "Secondary"], skill: "1H Blunt", delay: 38, damage: 8 },
  { id: "item:forged-pick", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 35, damage: 6 },
  { id: "item:forged-rapier", slots: ["Primary", "Secondary"], skill: "Piercing", delay: 26, damage: 5 },
  { id: "item:forged-scimitar", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 24, damage: 5 },
  { id: "item:forged-short-sword", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 24, damage: 4 },
  { id: "item:forged-spear", slots: ["Primary"], skill: "Piercing", delay: 28, damage: 6 },
  { id: "item:forged-two-handed-sword", slots: ["Primary"], skill: "2H Slashing", delay: 44, damage: 12 },
  { id: "item:forged-warhammer", slots: ["Primary", "Secondary"], skill: "1H Blunt", delay: 30, damage: 6 },
  { id: "item:forged-javelin", slots: ["Range", "Ammo"], skill: "Throwingv2", delay: 33, damage: 7 },
  { id: "item:forged-shuriken", slots: ["Range", "Ammo"], skill: "Throwingv2", delay: 25, damage: 4 },
  { id: "item:forged-throwing-axe", slots: ["Range", "Ammo"], skill: "Throwingv2", delay: 29, damage: 6 },
  { id: "item:forged-throwing-knife", slots: ["Range", "Ammo"], skill: "Throwingv2", delay: 35, damage: 5 },
  { id: "item:forged-fer-esh", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 30, damage: 5 },
  { id: "item:forged-shan-tok", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 38, damage: 8 },
  { id: "item:forged-sheer-blade", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 31, damage: 6 },
  { id: "item:tarnished-mining-pick", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 36, damage: 4 },
  { id: "item:tarnished-shortened-spear", slots: ["Primary", "Secondary"], skill: "Piercing", delay: 30, damage: 4 },
  { id: "item:tarnished-rapier", slots: ["Primary", "Secondary"], skill: "Piercing", delay: 29, damage: 4 },
  { id: "item:tarnished-short-sword", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 26, damage: 4 },
  { id: "item:tarnished-warhammer", slots: ["Primary", "Secondary"], skill: "1H Blunt", delay: 28, damage: 4 },
  { id: "item:tarnished-flail", slots: ["Primary", "Secondary"], skill: "1H Blunt", delay: 35, damage: 5 },
  { id: "item:tarnished-mace", slots: ["Primary", "Secondary"], skill: "1H Blunt", delay: 36, damage: 5 },
  { id: "item:tarnished-spear", slots: ["Primary"], skill: "Piercing", delay: 36, damage: 5 },
  { id: "item:tarnished-axe", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 34, damage: 5 },
  { id: "item:tarnished-broad-sword", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 34, damage: 5 },
  { id: "item:tarnished-long-sword", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 33, damage: 5 },
  { id: "item:tarnished-battle-axe", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 40, damage: 6 },
  { id: "item:tarnished-halberd", slots: ["Primary"], skill: "2H Slashing", delay: 55, damage: 11 },
  { id: "item:tarnished-morning-star", slots: ["Primary", "Secondary"], skill: "1H Blunt", delay: 42, damage: 6 },
  { id: "item:tarnished-scythe", slots: ["Primary"], skill: "2H Slashing", delay: 49, damage: 8 },
  { id: "item:tarnished-two-handed-sword", slots: ["Primary"], skill: "2H Slashing", delay: 48, damage: 9 },
  { id: "item:tarnished-two-handed-battle-axe", slots: ["Primary"], skill: "2H Slashing", delay: 47, damage: 9 },
  { id: "item:forged-velium-2-handed-sword", slots: ["Primary"], skill: "2H Slashing", delay: 43, damage: 13 },
  { id: "item:forged-velium-dagger", slots: ["Primary", "Secondary"], skill: "Piercing", delay: 18, damage: 3 },
  { id: "item:forged-velium-long-sword", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 28, damage: 7 },
  { id: "item:forged-velium-morning-star", slots: ["Primary", "Secondary"], skill: "1H Blunt", delay: 38, damage: 9 },
  { id: "item:forged-velium-scimitar", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 24, damage: 6 },
  { id: "item:forged-velium-short-sword", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 23, damage: 5 },
  { id: "item:forged-velium-shuriken", slots: ["Range", "Ammo"], skill: "Throwingv2", delay: 24, damage: 5 },
  { id: "item:forged-velium-throwing-axe", slots: ["Range", "Ammo"], skill: "Throwingv2", delay: 28, damage: 7 },
  { id: "item:forged-velium-throwing-knife", slots: ["Range", "Ammo"], skill: "Throwingv2", delay: 34, damage: 6 },
  { id: "item:forged-velium-throwing-spear", slots: ["Range", "Ammo"], skill: "Throwingv2", delay: 32, damage: 8 },
  { id: "item:seafarers-harpoon", slots: ["Primary"], skill: "Piercing", delay: 26, damage: 6 },
  { id: "item:seafarers-dirk", slots: ["Primary", "Secondary"], skill: "Piercing", delay: 22, damage: 4 },
  { id: "item:seafarers-cutlass", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 23, damage: 7 },
  { id: "item:seafarers-buckler-shield", slots: ["Secondary"] },
  { id: "item:enchanted-seafarers-cutlass", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 23, damage: 7 },
  { id: "item:enchanted-seafarers-dirk", slots: ["Primary", "Secondary"], skill: "Piercing", delay: 22, damage: 4 },
  { id: "item:enchanted-seafarers-harpoon", slots: ["Primary"], skill: "Piercing", delay: 26, damage: 6 },
  { id: "item:antonian-long-sword", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 28, damage: 8 },
  { id: "item:enchanted-antonian-long-sword-fire-emerald", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 26, damage: 9 },
  { id: "item:enchanted-antonian-long-sword-star-ruby", slots: ["Primary", "Secondary"], skill: "1H Slashing", delay: 26, damage: 9 },
  { id: "item:seafarer-ring-mask", slots: ["Face"] },
  { id: "item:seafarer-ring-gorget", slots: ["Neck"] },
  { id: "item:seafarer-ring-bracer", slots: ["Wrist"] },
  { id: "item:seafarer-ring-boots", slots: ["Feet"] },
  { id: "item:seafarer-ring-helm", slots: ["Head"] },
  { id: "item:seafarer-ring-mantle", slots: ["Shoulders"] },
  { id: "item:seafarer-ring-belt", slots: ["Waist"] },
  { id: "item:seafarer-ring-sleeves", slots: ["Arms"] },
  { id: "item:seafarer-ring-gauntlets", slots: ["Hands"] },
  { id: "item:seafarer-ring-mail", slots: ["Chest"] },
  { id: "item:seafarer-ring-cloak", slots: ["Back"] },
  { id: "item:seafarer-ring-leggings", slots: ["Legs"] },
  { id: "item:field-plate-visor", slots: ["Face"] },
  { id: "item:field-plate-collar", slots: ["Neck"] },
  { id: "item:field-plate-boots", slots: ["Feet"] },
  { id: "item:field-plate-bracers", slots: ["Wrist"] },
  { id: "item:field-plate-helm", slots: ["Head"] },
  { id: "item:field-plate-pauldron", slots: ["Shoulders"] },
  { id: "item:field-plate-girdle", slots: ["Waist"] },
  { id: "item:field-plate-vambraces", slots: ["Arms"] },
  { id: "item:field-plate-gauntlets", slots: ["Hands"] },
  { id: "item:field-breastplate", slots: ["Chest"] },
  { id: "item:field-plate-cloak", slots: ["Back"] },
  { id: "item:field-plate-greaves", slots: ["Legs"] },
  { id: "item:silver-full-breastplate", slots: ["Chest"] },
  { id: "item:silver-full-plate-boots", slots: ["Feet"] },
  { id: "item:silver-full-plate-bracer", slots: ["Wrist"] },
  { id: "item:silver-full-plate-collar", slots: ["Neck"] },
  { id: "item:silver-full-plate-gauntlets", slots: ["Hands"] },
  { id: "item:silver-full-plate-girdle", slots: ["Waist"] },
  { id: "item:silver-full-plate-greaves", slots: ["Legs"] },
  { id: "item:silver-full-plate-helm", slots: ["Head"] },
  { id: "item:silver-full-plate-pauldron", slots: ["Shoulders"] },
  { id: "item:silver-full-plate-vambraces", slots: ["Arms"] },
  { id: "item:silver-full-plate-visor", slots: ["Face"] },
  { id: "item:silver-full-splinted-cloak", slots: ["Back"] },
  { id: "item:electrum-full-breastplate", slots: ["Chest"] },
  { id: "item:electrum-full-plate-boots", slots: ["Feet"] },
  { id: "item:electrum-full-plate-bracer", slots: ["Wrist"] },
  { id: "item:electrum-full-plate-collar", slots: ["Neck"] },
  { id: "item:electrum-full-plate-gauntlets", slots: ["Hands"] },
  { id: "item:electrum-full-plate-girdle", slots: ["Waist"] },
  { id: "item:electrum-full-plate-greaves", slots: ["Legs"] },
  { id: "item:electrum-full-plate-helm", slots: ["Head"] },
  { id: "item:electrum-full-plate-pauldron", slots: ["Shoulders"] },
  { id: "item:electrum-full-plate-vambraces", slots: ["Arms"] },
  { id: "item:electrum-full-plate-visor", slots: ["Face"] },
  { id: "item:electrum-full-splinted-cloak", slots: ["Back"] },
  { id: "item:gold-full-breastplate", slots: ["Chest"] },
  { id: "item:gold-full-plate-boots", slots: ["Feet"] },
  { id: "item:gold-full-plate-bracer", slots: ["Wrist"] },
  { id: "item:gold-full-plate-collar", slots: ["Neck"] },
  { id: "item:gold-full-plate-gauntlets", slots: ["Hands"] },
  { id: "item:gold-full-plate-girdle", slots: ["Waist"] },
  { id: "item:gold-full-plate-greaves", slots: ["Legs"] },
  { id: "item:gold-full-plate-helm", slots: ["Head"] },
  { id: "item:gold-full-plate-pauldron", slots: ["Shoulders"] },
  { id: "item:gold-full-plate-vambraces", slots: ["Arms"] },
  { id: "item:gold-full-plate-visor", slots: ["Face"] },
  { id: "item:gold-full-splinted-cloak", slots: ["Back"] },
  { id: "item:platinum-full-breastplate", slots: ["Chest"] },
  { id: "item:platinum-full-plate-boots", slots: ["Feet"] },
  { id: "item:platinum-full-plate-bracer", slots: ["Wrist"] },
  { id: "item:platinum-full-plate-collar", slots: ["Neck"] },
  { id: "item:platinum-full-plate-gauntlets", slots: ["Hands"] },
  { id: "item:platinum-full-plate-girdle", slots: ["Waist"] },
  { id: "item:platinum-full-plate-greaves", slots: ["Legs"] },
  { id: "item:platinum-full-plate-helm", slots: ["Head"] },
  { id: "item:platinum-full-plate-pauldron", slots: ["Shoulders"] },
  { id: "item:platinum-full-plate-vambraces", slots: ["Arms"] },
  { id: "item:platinum-full-plate-visor", slots: ["Face"] },
  { id: "item:platinum-full-splinted-cloak", slots: ["Back"] },
  { id: "item:enchanted-full-breastplate-silver", slots: ["Chest"] },
  { id: "item:enchanted-full-plate-boots-silver", slots: ["Feet"] },
  { id: "item:enchanted-full-plate-bracers-silver", slots: ["Wrist"] },
  { id: "item:enchanted-full-plate-collar-silver", slots: ["Neck"] },
  { id: "item:enchanted-full-plate-gauntlets-silver", slots: ["Hands"] },
  { id: "item:enchanted-full-plate-girdle-silver", slots: ["Waist"] },
  { id: "item:enchanted-full-plate-greaves-silver", slots: ["Legs"] },
  { id: "item:enchanted-full-plate-helm-silver", slots: ["Head"] },
  { id: "item:enchanted-full-plate-pauldron-silver", slots: ["Shoulders"] },
  { id: "item:enchanted-full-plate-vambraces-silver", slots: ["Arms"] },
  { id: "item:enchanted-full-plate-visor-silver", slots: ["Face"] },
  { id: "item:enchanted-full-splinted-cloak-silver", slots: ["Back"] },
  { id: "item:enchanted-full-breastplate-electrum", slots: ["Chest"] },
  { id: "item:enchanted-full-plate-boots-electrum", slots: ["Feet"] },
  { id: "item:enchanted-full-plate-bracers-electrum", slots: ["Wrist"] },
  { id: "item:enchanted-full-plate-collar-electrum", slots: ["Neck"] },
  { id: "item:enchanted-full-plate-gauntlets-electrum", slots: ["Hands"] },
  { id: "item:enchanted-full-plate-girdle-electrum", slots: ["Waist"] },
  { id: "item:enchanted-full-plate-greaves-electrum", slots: ["Legs"] },
  { id: "item:enchanted-full-plate-helm-electrum", slots: ["Head"] },
  { id: "item:enchanted-full-plate-pauldron-electrum", slots: ["Shoulders"] },
  { id: "item:enchanted-full-plate-vambraces-electrum", slots: ["Arms"] },
  { id: "item:enchanted-full-plate-visor-electrum", slots: ["Face"] },
  { id: "item:enchanted-full-splinted-cloak-electrum", slots: ["Back"] },
  { id: "item:enchanted-full-breastplate-gold", slots: ["Chest"] },
  { id: "item:enchanted-full-plate-boots-gold", slots: ["Feet"] },
  { id: "item:enchanted-full-plate-bracers-gold", slots: ["Wrist"] },
  { id: "item:enchanted-full-plate-collar-gold", slots: ["Neck"] },
  { id: "item:enchanted-full-plate-gauntlets-gold", slots: ["Hands"] },
  { id: "item:enchanted-full-plate-girdle-gold", slots: ["Waist"] },
  { id: "item:enchanted-full-plate-greaves-gold", slots: ["Legs"] },
  { id: "item:enchanted-full-plate-helm-gold", slots: ["Head"] },
  { id: "item:enchanted-full-plate-pauldron-gold", slots: ["Shoulders"] },
  { id: "item:enchanted-full-plate-vambraces-gold", slots: ["Arms"] },
  { id: "item:enchanted-full-plate-visor-gold", slots: ["Face"] },
  { id: "item:enchanted-full-splinted-cloak-gold", slots: ["Back"] },
  { id: "item:enchanted-full-breastplate-platinum", slots: ["Chest"] },
  { id: "item:enchanted-full-plate-boots-platinum", slots: ["Feet"] },
  { id: "item:enchanted-full-plate-bracers-platinum", slots: ["Wrist"] },
  { id: "item:enchanted-full-plate-collar-platinum", slots: ["Neck"] },
  { id: "item:enchanted-full-plate-gauntlets-platinum", slots: ["Hands"] },
  { id: "item:enchanted-full-plate-girdle-platinum", slots: ["Waist"] },
  { id: "item:enchanted-full-plate-greaves-platinum", slots: ["Legs"] },
  { id: "item:enchanted-full-plate-helm-platinum", slots: ["Head"] },
  { id: "item:enchanted-full-plate-pauldron-platinum", slots: ["Shoulders"] },
  { id: "item:enchanted-full-plate-vambraces-platinum", slots: ["Arms"] },
  { id: "item:enchanted-full-plate-visor-platinum", slots: ["Face"] },
  { id: "item:enchanted-full-splinted-cloak-platinum", slots: ["Back"] },
  { id: "item:imbued-field-breastplate-bertoxxulous", slots: ["Chest"] },
  { id: "item:imbued-field-plate-pauldron-bertoxxulous", slots: ["Shoulders"] },
  { id: "item:imbued-field-plate-vambraces-bertoxxulous", slots: ["Arms"] },
  { id: "item:imbued-field-plate-visor-bertoxxulous", slots: ["Face"] },
  { id: "item:imbued-field-plate-helm-bertoxxulous", slots: ["Head"] },
  { id: "item:imbued-field-plate-greaves-bertoxxulous", slots: ["Legs"] },
  { id: "item:imbued-field-plate-girdle-bertoxxulous", slots: ["Waist"] },
  { id: "item:imbued-field-plate-gauntlets-bertoxxulous", slots: ["Hands"] },
  { id: "item:imbued-field-plate-collar-bertoxxulous", slots: ["Neck"] },
  { id: "item:imbued-field-plate-cloak-bertoxxulous", slots: ["Back"] },
  { id: "item:imbued-field-plate-bracers-bertoxxulous", slots: ["Wrist"] },
  { id: "item:imbued-field-plate-boots-bertoxxulous", slots: ["Feet"] },
  { id: "item:imbued-field-breastplate-erollisi-marr", slots: ["Chest"] },
  { id: "item:imbued-field-plate-pauldron-erollisi-marr", slots: ["Shoulders"] },
  { id: "item:imbued-field-plate-vambraces-erollisi-marr", slots: ["Arms"] },
  { id: "item:imbued-field-plate-visor-erollisi-marr", slots: ["Face"] },
  { id: "item:imbued-field-plate-helm-erollisi-marr", slots: ["Head"] },
  { id: "item:imbued-field-plate-greaves-erollisi-marr", slots: ["Legs"] },
  { id: "item:imbued-field-plate-girdle-erollisi-marr", slots: ["Waist"] },
  { id: "item:imbued-field-plate-gauntlets-erollisi-marr", slots: ["Hands"] },
  { id: "item:imbued-field-plate-collar-erollisi-marr", slots: ["Neck"] },
  { id: "item:imbued-field-plate-cloak-erollisi-marr", slots: ["Back"] },
  { id: "item:imbued-field-plate-bracers-erollisi-marr", slots: ["Wrist"] },
  { id: "item:imbued-field-plate-boots-erollisi-marr", slots: ["Feet"] },
  { id: "item:imbued-field-breastplate-innoruuk", slots: ["Chest"] },
  { id: "item:imbued-field-plate-pauldron-innoruuk", slots: ["Shoulders"] },
  { id: "item:imbued-field-plate-vambraces-innoruuk", slots: ["Arms"] },
  { id: "item:imbued-field-plate-visor-innoruuk", slots: ["Face"] },
  { id: "item:imbued-field-plate-helm-innoruuk", slots: ["Head"] },
  { id: "item:imbued-field-plate-greaves-innoruuk", slots: ["Legs"] },
  { id: "item:imbued-field-plate-girdle-innoruuk", slots: ["Waist"] },
  { id: "item:imbued-field-plate-gauntlets-innoruuk", slots: ["Hands"] },
  { id: "item:imbued-field-plate-collar-innoruuk", slots: ["Neck"] },
  { id: "item:imbued-field-plate-cloak-innoruuk", slots: ["Back"] },
  { id: "item:imbued-field-plate-bracers-innoruuk", slots: ["Wrist"] },
  { id: "item:imbued-field-plate-boots-innoruuk", slots: ["Feet"] },
  { id: "item:imbued-field-breastplate-karana", slots: ["Chest"] },
  { id: "item:imbued-field-plate-pauldron-karana", slots: ["Shoulders"] },
  { id: "item:imbued-field-plate-vambraces-karana", slots: ["Arms"] },
  { id: "item:imbued-field-plate-visor-karana", slots: ["Face"] },
  { id: "item:imbued-field-plate-helm-karana", slots: ["Head"] },
  { id: "item:imbued-field-plate-greaves-karana", slots: ["Legs"] },
  { id: "item:imbued-field-plate-girdle-karana", slots: ["Waist"] },
  { id: "item:imbued-field-plate-gauntlets-karana", slots: ["Hands"] },
  { id: "item:imbued-field-plate-collar-karana", slots: ["Neck"] },
  { id: "item:imbued-field-plate-cloak-karana", slots: ["Back"] },
  { id: "item:imbued-field-plate-bracers-karana", slots: ["Wrist"] },
  { id: "item:imbued-field-plate-boots-karana", slots: ["Feet"] },
  { id: "item:imbued-field-breastplate-mithaniel-marr", slots: ["Chest"] },
  { id: "item:imbued-field-plate-pauldron-mithaniel-marr", slots: ["Shoulders"] },
  { id: "item:imbued-field-plate-vambraces-mithaniel-marr", slots: ["Arms"] },
  { id: "item:imbued-field-plate-visor-mithaniel-marr", slots: ["Face"] },
  { id: "item:imbued-field-plate-helm-mithaniel-marr", slots: ["Head"] },
  { id: "item:imbued-field-plate-greaves-mithaniel-marr", slots: ["Legs"] },
  { id: "item:imbued-field-plate-girdle-mithaniel-marr", slots: ["Waist"] },
  { id: "item:imbued-field-plate-gauntlets-mithaniel-marr", slots: ["Hands"] },
  { id: "item:imbued-field-plate-collar-mithaniel-marr", slots: ["Neck"] },
  { id: "item:imbued-field-plate-cloak-mithaniel-marr", slots: ["Back"] },
  { id: "item:imbued-field-plate-bracers-mithaniel-marr", slots: ["Wrist"] },
  { id: "item:imbued-field-plate-boots-mithaniel-marr", slots: ["Feet"] },
  { id: "item:imbued-field-breastplate-rallos-zek", slots: ["Chest"] },
  { id: "item:imbued-field-plate-pauldron-rallos-zek", slots: ["Shoulders"] },
  { id: "item:imbued-field-plate-vambraces-rallos-zek", slots: ["Arms"] },
  { id: "item:imbued-field-plate-visor-rallos-zek", slots: ["Face"] },
  { id: "item:imbued-field-plate-helm-rallos-zek", slots: ["Head"] },
  { id: "item:imbued-field-plate-greaves-rallos-zek", slots: ["Legs"] },
  { id: "item:imbued-field-plate-girdle-rallos-zek", slots: ["Waist"] },
  { id: "item:imbued-field-plate-gauntlets-rallos-zek", slots: ["Hands"] },
  { id: "item:imbued-field-plate-collar-rallos-zek", slots: ["Neck"] },
  { id: "item:imbued-field-plate-cloak-rallos-zek", slots: ["Back"] },
  { id: "item:imbued-field-plate-bracers-rallos-zek", slots: ["Wrist"] },
  { id: "item:imbued-field-plate-boots-rallos-zek", slots: ["Feet"] },
  { id: "item:imbued-field-breastplate-rodcet-nife", slots: ["Chest"] },
  { id: "item:imbued-field-plate-pauldron-rodcet-nife", slots: ["Shoulders"] },
  { id: "item:imbued-field-plate-vambraces-rodcet-nife", slots: ["Arms"] },
  { id: "item:imbued-field-plate-visor-rodcet-nife", slots: ["Face"] },
  { id: "item:imbued-field-plate-helm-rodcet-nife", slots: ["Head"] },
  { id: "item:imbued-field-plate-greaves-rodcet-nife", slots: ["Legs"] },
  { id: "item:imbued-field-plate-girdle-rodcet-nife", slots: ["Waist"] },
  { id: "item:imbued-field-plate-gauntlets-rodcet-nife", slots: ["Hands"] },
  { id: "item:imbued-field-plate-collar-rodcet-nife", slots: ["Neck"] },
  { id: "item:imbued-field-plate-cloak-rodcet-nife", slots: ["Back"] },
  { id: "item:imbued-field-plate-bracers-rodcet-nife", slots: ["Wrist"] },
  { id: "item:imbued-field-plate-boots-rodcet-nife", slots: ["Feet"] },
];

for (const u of updates) {
  const { id, ...fields } = u;
  updateNode(id, fields);
}

save();
console.log(`Updated ${updates.length} items with slots/skill/damage/delay.`);
