/**
 * Migration 387: comprehensive stat-block backfill for every Blacksmithing
 * produced item (armor + weapons + tradeskill containers), sourced in one
 * pass this time -- migration 386 only captured `slots`/`skill`/`damage`/
 * `delay` (just enough for the Item Type/Subtype filter), leaving Browse's
 * recipe cards with nothing to show for *why* you'd want the produced item
 * (no AC, no class restriction, no stat bonuses) even after that pass.
 * This migration re-fetches the same 322 items' eqlwiki pages (raw
 * wikitext, same batched-multi-title technique as 386) and parses every
 * `{{Itempage}}` statsblock field this batch actually has: AC, WT/Size,
 * STR/STA/AGI/DEX/WIS/INT/CHA, SV resists, MAGIC ITEM, Effect, and the
 * tradeskill-container Capacity/Size Capacity pair (5 items: Small/Medium/
 * Large Metal Container, Toolbox, Small Sewing Kit) -- all real fields
 * already in item-node-schema.md, none invented.
 *
 * `classes` is resolved from each item's own wiki Category tags (e.g.
 * `[[Category:Warrior Equipment]]`), not parsed from the statsblock's own
 * "Class: ALL except X Y Z" line -- same precedent item-node-schema.md
 * already documents for Small Scarab Helm, and it sidesteps having to
 * hand-maintain the exact roster "ALL" resolves against. Category tags also
 * include non-class "X Worshiper Equipment" tags on deity-imbued armor,
 * filtered out against a real class-name allowlist rather than accepted as
 * "X Equipment" generically.
 *
 * `deity` is a new item-node-schema.md field, added this migration: 84 of
 * these 322 items (the Imbued Field Plate sets, one per deity) carry a real
 * `Deity: <name>` restriction line on their own wiki page -- directly
 * relevant to this app's own faction system (worst-of race/class/deity),
 * not just flavor text, so it earns a real field rather than being dropped
 * or folded into `classes`.
 *
 * Race was checked too (322 items, only one non-"ALL" value: Tarnished
 * Halberd's "ALL except IKS") -- a single outlier doesn't clear the "real
 * data demands a field" bar item-node-schema.md sets, so it's left
 * unrecorded rather than adding a race field for one item's exception.
 */

import { loadGraph } from "./_lib";

const { updateNode, save } = loadGraph(import.meta.dir);

interface Update {
  id: string;
  slots?: string[];
  skill?: string;
  delay?: number;
  damage?: number;
  ac?: number;
  weight?: number;
  size?: string;
  capacity?: number;
  containerSize?: string;
  stats?: Record<string, number>;
  resists?: Record<string, number>;
  deity?: string;
  effect?: string;
  magic?: boolean;
  lore?: boolean;
  noTrade?: boolean;
  classes: string[];
}

const updates: Update[] = [
  {"id":"item:small-brick-of-ore","weight":15,"size":"Small","classes":[]},
  {"id":"item:sheet-metal","weight":2,"size":"Tiny","classes":[]},
  {"id":"item:file","weight":0.1,"size":"Tiny","classes":[]},
  {"id":"item:large-lantern","slots":["Secondary"],"weight":1,"size":"Small","classes":["bard","cleric","druid","enchanter","magician","monk","necromancer","paladin","ranger","rogue","shaman","shadow knight","warrior","wizard"]},
  {"id":"item:banded-mask","slots":["Face"],"ac":4,"weight":1,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-gorget","slots":["Neck"],"ac":5,"weight":2,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-bracer","slots":["Wrist"],"ac":6,"weight":2,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-boots","slots":["Feet"],"ac":6,"weight":5,"size":"Medium","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-belt","slots":["Waist"],"ac":6,"weight":2.5,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-mantle","slots":["Shoulders"],"ac":6,"weight":3.5,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-cloak","slots":["Back"],"ac":7,"weight":4,"size":"Large","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-gauntlets","slots":["Hands"],"ac":7,"weight":4,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-sleeves","slots":["Arms"],"ac":7,"weight":3.5,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-helm","slots":["Head"],"ac":8,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-leggings","slots":["Legs"],"ac":8,"weight":5.5,"size":"Medium","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:banded-mail","slots":["Chest"],"ac":15,"weight":7.5,"size":"Medium","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:small-metal-container","weight":3,"capacity":2,"containerSize":"Medium","classes":[]},
  {"id":"item:medium-metal-container","weight":4.5,"capacity":4,"containerSize":"Medium","classes":[]},
  {"id":"item:large-metal-container","weight":6,"capacity":8,"containerSize":"Medium","classes":[]},
  {"id":"item:skinning-knife","slots":["Primary","Secondary"],"skill":"Piercing","delay":25,"damage":2,"weight":2,"size":"Small","classes":["bard","enchanter","magician","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:scaler","weight":0.1,"size":"Tiny","classes":[]},
  {"id":"item:toolbox","weight":3,"capacity":8,"containerSize":"Giant","classes":[]},
  {"id":"item:muffin-tin","weight":0.1,"size":"Small","classes":[]},
  {"id":"item:pie-tin","weight":0.1,"size":"Small","classes":[]},
  {"id":"item:cake-round","weight":0.1,"size":"Small","classes":[]},
  {"id":"item:bread-tin","weight":0.1,"size":"Small","classes":[]},
  {"id":"item:skewers","weight":0.1,"size":"Small","classes":[]},
  {"id":"item:small-sewing-kit","weight":0.4,"capacity":2,"containerSize":"Large","classes":[]},
  {"id":"item:buckler","slots":["Secondary"],"ac":4,"weight":3,"size":"Small","classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:round-shield","slots":["Secondary"],"ac":6,"weight":5,"size":"Medium","classes":["bard","cleric","druid","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:large-brick-of-ore","weight":25.5,"size":"Small","classes":[]},
  {"id":"item:block-of-ore","weight":25.5,"size":"Small","classes":[]},
  {"id":"item:folded-sheet-metal","weight":0.1,"size":"Tiny","classes":[]},
  {"id":"item:studs","weight":0.1,"size":"Tiny","classes":[]},
  {"id":"item:steel-boning","weight":0.1,"size":"Tiny","classes":[]},
  {"id":"item:medium-quality-folded-sheet-metal","weight":15,"size":"Small","classes":[]},
  {"id":"item:targ-shield","slots":["Secondary"],"ac":7,"weight":7.5,"size":"Medium","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:kite-shield","slots":["Secondary"],"ac":8,"weight":10,"size":"Large","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:tower-shield","slots":["Secondary"],"ac":10,"weight":15,"size":"Large","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:field-point-arrowheads","weight":0.1,"size":"Small","classes":[]},
  {"id":"item:hooked-arrowheads","weight":0.1,"size":"Small","classes":[]},
  {"id":"item:antonian-javelin","slots":["Range","Ammo"],"skill":"Throwingv2","delay":30,"damage":8,"weight":1.5,"size":"Large","classes":["bard","monk","ranger","rogue","shaman","warrior"]},
  {"id":"item:bundled-steel-arrow-shafts","weight":0.1,"size":"Small","classes":[]},
  {"id":"item:silver-tipped-arrowheads","weight":0.1,"size":"Small","magic":true,"classes":[]},
  {"id":"item:forged-bastard-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":33,"damage":7,"weight":6.5,"size":"Medium","classes":["bard","druid","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-battle-axe","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":34,"damage":7,"weight":8.5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-dagger","slots":["Primary","Secondary"],"skill":"Piercing","delay":21,"damage":3,"weight":2.5,"size":"Small","classes":["bard","enchanter","magician","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:forged-halberd","slots":["Primary"],"skill":"2H Slashing","delay":48,"damage":14,"weight":14,"size":"Giant","classes":["paladin","ranger","shadow knight","warrior"]},
  {"id":"item:forged-long-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":28,"damage":6,"weight":7.5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-mace","slots":["Primary","Secondary"],"skill":"1H Blunt","delay":36,"damage":7,"weight":8,"size":"Medium","classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:forged-morning-star","slots":["Primary","Secondary"],"skill":"1H Blunt","delay":38,"damage":8,"weight":9,"size":"Medium","classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:forged-pick","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":35,"damage":6,"weight":6.5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:forged-rapier","slots":["Primary","Secondary"],"skill":"Piercing","delay":26,"damage":5,"weight":5,"size":"Medium","classes":["bard","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-scimitar","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":24,"damage":5,"weight":7.5,"size":"Medium","classes":["bard","druid","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-short-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":24,"damage":4,"weight":5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-spear","slots":["Primary"],"skill":"Piercing","delay":28,"damage":6,"weight":7,"size":"Large","classes":["bard","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:forged-two-handed-sword","slots":["Primary"],"skill":"2H Slashing","delay":44,"damage":12,"weight":11,"size":"Large","classes":["paladin","ranger","shadow knight","warrior"]},
  {"id":"item:forged-warhammer","slots":["Primary","Secondary"],"skill":"1H Blunt","delay":30,"damage":6,"weight":7.5,"size":"Medium","classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:forged-javelin","slots":["Range","Ammo"],"skill":"Throwingv2","delay":33,"damage":7,"weight":2,"size":"Large","classes":["bard","monk","ranger","rogue","warrior"]},
  {"id":"item:forged-shuriken","slots":["Range","Ammo"],"skill":"Throwingv2","delay":25,"damage":4,"weight":0.5,"size":"Small","classes":["bard","enchanter","magician","monk","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:forged-throwing-axe","slots":["Range","Ammo"],"skill":"Throwingv2","delay":29,"damage":6,"weight":1,"size":"Medium","classes":["bard","enchanter","magician","monk","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:forged-throwing-knife","slots":["Range","Ammo"],"skill":"Throwingv2","delay":35,"damage":5,"weight":0.5,"size":"Small","classes":["bard","enchanter","magician","monk","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:forged-fer-esh","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":30,"damage":5,"weight":7.5,"size":"Medium","classes":["bard","druid","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-shan-tok","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":38,"damage":8,"weight":10,"size":"Large","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-sheer-blade","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":31,"damage":6,"weight":8.5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:tarnished-dagger","slots":["Primary","Secondary"],"skill":"Piercing","delay":22,"damage":3,"weight":2.5,"size":"Small","classes":["bard","enchanter","magician","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:tarnished-mining-pick","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":36,"damage":4,"weight":6.5,"size":"Medium","classes":["bard","enchanter","magician","necromancer","paladin","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:tarnished-shortened-spear","slots":["Primary","Secondary"],"skill":"Piercing","delay":30,"damage":4,"weight":5,"size":"Medium","classes":["bard","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:tarnished-rapier","slots":["Primary","Secondary"],"skill":"Piercing","delay":29,"damage":4,"weight":5,"size":"Medium","classes":["bard","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:tarnished-short-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":26,"damage":4,"weight":5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:tarnished-warhammer","slots":["Primary","Secondary"],"skill":"1H Blunt","delay":28,"damage":4,"weight":7.5,"size":"Medium","classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:tarnished-flail","slots":["Primary","Secondary"],"skill":"1H Blunt","delay":35,"damage":5,"weight":9,"size":"Medium","classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:tarnished-mace","slots":["Primary","Secondary"],"skill":"1H Blunt","delay":36,"damage":5,"weight":8,"size":"Medium","classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:tarnished-spear","slots":["Primary"],"skill":"Piercing","delay":36,"damage":5,"weight":7,"size":"Large","classes":["bard","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:tarnished-axe","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":34,"damage":5,"weight":6.5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:tarnished-broad-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":34,"damage":5,"weight":7.5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:tarnished-long-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":33,"damage":5,"weight":7.5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:tarnished-scimitar","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":33,"damage":5,"weight":7.5,"size":"Medium","classes":["bard","druid","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:tarnished-battle-axe","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":40,"damage":6,"weight":8.5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:tarnished-halberd","slots":["Primary"],"skill":"2H Slashing","delay":55,"damage":11,"weight":14,"size":"Giant","classes":["paladin","ranger","shadow knight","warrior"]},
  {"id":"item:tarnished-morning-star","slots":["Primary","Secondary"],"skill":"1H Blunt","delay":42,"damage":6,"weight":10,"size":"Medium","classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:tarnished-bastard-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":40,"damage":6,"weight":9,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:tarnished-scythe","slots":["Primary"],"skill":"2H Slashing","delay":49,"damage":8,"weight":12,"size":"Large","classes":["paladin","ranger","shadow knight","warrior"]},
  {"id":"item:tarnished-two-handed-sword","slots":["Primary"],"skill":"2H Slashing","delay":48,"damage":9,"weight":12,"size":"Large","classes":["paladin","ranger","shadow knight","warrior"]},
  {"id":"item:tarnished-two-handed-battle-axe","slots":["Primary"],"skill":"2H Slashing","delay":47,"damage":9,"weight":13,"size":"Large","classes":["paladin","ranger","shadow knight","warrior"]},
  {"id":"item:sheet-of-velium","weight":15,"size":"Small","classes":[]},
  {"id":"item:forged-velium-2-handed-sword","slots":["Primary"],"skill":"2H Slashing","delay":43,"damage":13,"weight":9,"size":"Large","effect":"Velium Shards (Combat, Casting Time: Instant) at Level 25","magic":true,"classes":["paladin","ranger","shadow knight","warrior"]},
  {"id":"item:forged-velium-dagger","slots":["Primary","Secondary"],"skill":"Piercing","delay":18,"damage":3,"weight":3.9,"size":"Small","effect":"Velium Shards (Combat, Casting Time: Instant) at Level 25","magic":true,"classes":["bard","enchanter","magician","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:forged-velium-long-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":28,"damage":7,"weight":4.5,"size":"Medium","effect":"Velium Shards (Combat, Casting Time: Instant) at Level 25","magic":true,"classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-velium-morning-star","slots":["Primary","Secondary"],"skill":"1H Blunt","delay":38,"damage":9,"weight":9.5,"size":"Medium","effect":"Velium Shards (Combat, Casting Time: Instant) at Level 25","magic":true,"classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:forged-velium-scimitar","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":24,"damage":6,"weight":4.5,"size":"Medium","effect":"Velium Shards (Combat, Casting Time: Instant) at Level 25","magic":true,"classes":["bard","druid","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-velium-short-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":23,"damage":5,"weight":3.5,"size":"Medium","effect":"Velium Shards (Combat, Casting Time: Instant) at Level 25","magic":true,"classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:forged-velium-shuriken","slots":["Range","Ammo"],"skill":"Throwingv2","delay":24,"damage":5,"weight":0.3,"size":"Small","magic":true,"classes":["bard","enchanter","magician","monk","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:forged-velium-throwing-axe","slots":["Range","Ammo"],"skill":"Throwingv2","delay":28,"damage":7,"weight":0.8,"size":"Medium","magic":true,"classes":["bard","enchanter","magician","monk","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:forged-velium-throwing-knife","slots":["Range","Ammo"],"skill":"Throwingv2","delay":34,"damage":6,"weight":0.3,"size":"Small","magic":true,"classes":["bard","enchanter","magician","monk","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:forged-velium-throwing-spear","slots":["Range","Ammo"],"skill":"Throwingv2","delay":32,"damage":8,"weight":1.5,"size":"Large","magic":true,"classes":["bard","monk","ranger","rogue","warrior"]},
  {"id":"container:pot","weight":0.3,"size":"Small","classes":[]},
  {"id":"container:smoker","weight":0.4,"size":"Small","classes":[]},
  {"id":"item:small-brick-of-high-quality-ore","weight":7,"size":"Small","classes":[]},
  {"id":"item:block-of-high-quality-ore","weight":18,"size":"Small","classes":[]},
  {"id":"item:high-quality-sheet-metal","weight":15,"size":"Small","classes":[]},
  {"id":"item:high-quality-folded-sheet-metal","weight":15,"size":"Small","classes":[]},
  {"id":"item:small-brick-of-enchanted-ore","weight":7,"size":"Small","classes":[]},
  {"id":"item:enchanted-sheet-metal","weight":15,"size":"Small","classes":[]},
  {"id":"item:block-of-enchanted-ore","weight":18,"size":"Small","classes":[]},
  {"id":"item:enchanted-folded-sheet-metal","weight":15,"size":"Small","classes":[]},
  {"id":"item:seafarers-harpoon","slots":["Primary"],"skill":"Piercing","delay":26,"damage":6,"weight":7,"size":"Large","classes":["bard","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarers-dirk","slots":["Primary","Secondary"],"skill":"Piercing","delay":22,"damage":4,"weight":2.5,"size":"Small","classes":["bard","enchanter","magician","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:seafarers-cutlass","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":23,"damage":7,"weight":7,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:seafarers-buckler-shield","slots":["Secondary"],"ac":7,"weight":3,"size":"Small","stats":{"dex":2},"classes":["bard","cleric","druid","monk","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:enchanted-seafarers-cutlass","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":23,"damage":7,"weight":7,"size":"Medium","stats":{"agi":4,"dex":4},"magic":true,"classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:enchanted-seafarers-dirk","slots":["Primary","Secondary"],"skill":"Piercing","delay":22,"damage":4,"weight":2.5,"size":"Small","stats":{"agi":2,"dex":2},"magic":true,"classes":["bard","enchanter","magician","necromancer","ranger","rogue","shadow knight","warrior","wizard"]},
  {"id":"item:enchanted-seafarers-harpoon","slots":["Primary"],"skill":"Piercing","delay":26,"damage":6,"weight":7,"size":"Large","stats":{"dex":2},"resists":{"cold":3},"magic":true,"classes":["bard","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:high-quality-metal-rings","weight":4,"size":"Small","classes":[]},
  {"id":"item:enchanted-chain-jointing","weight":4,"size":"Small","classes":[]},
  {"id":"item:antonian-long-sword","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":28,"damage":8,"weight":7.5,"size":"Medium","classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:enchanted-antonian-long-sword-fire-emerald","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":26,"damage":9,"weight":7.5,"size":"Medium","stats":{"str":2,"dex":2},"magic":true,"classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:enchanted-antonian-long-sword-star-ruby","slots":["Primary","Secondary"],"skill":"1H Slashing","delay":26,"damage":9,"weight":7.5,"size":"Medium","stats":{"dex":3,"cha":3},"magic":true,"classes":["bard","paladin","ranger","rogue","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-mask","slots":["Face"],"ac":6,"weight":1.5,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-gorget","slots":["Neck"],"ac":7,"weight":2.5,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-bracer","slots":["Wrist"],"ac":8,"weight":2.5,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-boots","slots":["Feet"],"ac":9,"weight":5.5,"size":"Medium","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-helm","slots":["Head"],"ac":10,"weight":5,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-mantle","slots":["Shoulders"],"ac":8,"weight":4,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-belt","slots":["Waist"],"ac":8,"weight":3,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-sleeves","slots":["Arms"],"ac":10,"weight":4,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-gauntlets","slots":["Hands"],"ac":9,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-mail","slots":["Chest"],"ac":18,"weight":8,"size":"Medium","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-cloak","slots":["Back"],"ac":9,"weight":4.5,"size":"Large","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:seafarer-ring-leggings","slots":["Legs"],"ac":12,"weight":6,"size":"Medium","classes":["bard","cleric","paladin","ranger","rogue","shaman","shadow knight","warrior"]},
  {"id":"item:field-plate-visor","slots":["Face"],"ac":6,"weight":1.7,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-collar","slots":["Neck"],"ac":8,"weight":4.2,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-boots","slots":["Feet"],"ac":12,"weight":7,"size":"Medium","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-bracers","slots":["Wrist"],"ac":10,"weight":4.2,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-helm","slots":["Head"],"ac":13,"weight":4.8,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-pauldron","slots":["Shoulders"],"ac":11,"weight":4.8,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-girdle","slots":["Waist"],"ac":9,"weight":4.2,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-vambraces","slots":["Arms"],"ac":13,"weight":6.8,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-gauntlets","slots":["Hands"],"ac":12,"weight":5.2,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-breastplate","slots":["Chest"],"ac":24,"weight":10.5,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-cloak","slots":["Back"],"ac":12,"weight":6,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:field-plate-greaves","slots":["Legs"],"ac":16,"weight":8,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-breastplate","slots":["Chest"],"ac":26,"weight":11,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-boots","slots":["Feet"],"ac":13,"weight":7.5,"size":"Medium","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-bracer","slots":["Wrist"],"ac":12,"weight":4.4,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-collar","slots":["Neck"],"ac":9,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-gauntlets","slots":["Hands"],"ac":14,"weight":5.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-girdle","slots":["Waist"],"ac":10,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-greaves","slots":["Legs"],"ac":18,"weight":8.5,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-helm","slots":["Head"],"ac":15,"weight":5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-pauldron","slots":["Shoulders"],"ac":13,"weight":5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-vambraces","slots":["Arms"],"ac":14,"weight":7,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-plate-visor","slots":["Face"],"ac":7,"weight":2,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:silver-full-splinted-cloak","slots":["Back"],"ac":14,"weight":6.5,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-breastplate","slots":["Chest"],"ac":26,"weight":11,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-boots","slots":["Feet"],"ac":13,"weight":7.5,"size":"Medium","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-bracer","slots":["Wrist"],"ac":12,"weight":4.4,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-collar","slots":["Neck"],"ac":9,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-gauntlets","slots":["Hands"],"ac":14,"weight":5.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-girdle","slots":["Waist"],"ac":10,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-greaves","slots":["Legs"],"ac":18,"weight":8.5,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-helm","slots":["Head"],"ac":15,"weight":5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-pauldron","slots":["Shoulders"],"ac":13,"weight":5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-vambraces","slots":["Arms"],"ac":14,"weight":7,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-plate-visor","slots":["Face"],"ac":7,"weight":2,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:electrum-full-splinted-cloak","slots":["Back"],"ac":14,"weight":6.5,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-breastplate","slots":["Chest"],"ac":26,"weight":11,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-boots","slots":["Feet"],"ac":13,"weight":7.5,"size":"Medium","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-bracer","slots":["Wrist"],"ac":12,"weight":4.4,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-collar","slots":["Neck"],"ac":9,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-gauntlets","slots":["Hands"],"ac":14,"weight":5.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-girdle","slots":["Waist"],"ac":10,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-greaves","slots":["Legs"],"ac":18,"weight":8.5,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-helm","slots":["Head"],"ac":15,"weight":5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-pauldron","slots":["Shoulders"],"ac":13,"weight":5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-vambraces","slots":["Arms"],"ac":14,"weight":7,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-plate-visor","slots":["Face"],"ac":7,"weight":2,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:gold-full-splinted-cloak","slots":["Back"],"ac":14,"weight":6.5,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-breastplate","slots":["Chest"],"ac":26,"weight":11,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-boots","slots":["Feet"],"ac":13,"weight":7.5,"size":"Medium","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-bracer","slots":["Wrist"],"ac":12,"weight":4.4,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-collar","slots":["Neck"],"ac":9,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-gauntlets","slots":["Hands"],"ac":14,"weight":5.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-girdle","slots":["Waist"],"ac":10,"weight":4.5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-greaves","slots":["Legs"],"ac":18,"weight":8.5,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-helm","slots":["Head"],"ac":15,"weight":5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-pauldron","slots":["Shoulders"],"ac":13,"weight":5,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-vambraces","slots":["Arms"],"ac":14,"weight":7,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-plate-visor","slots":["Face"],"ac":7,"weight":2,"size":"Small","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:platinum-full-splinted-cloak","slots":["Back"],"ac":14,"weight":6.5,"size":"Large","classes":["bard","cleric","paladin","shadow knight","warrior"]},
  {"id":"item:enchanted-full-breastplate-silver","slots":["Chest"],"ac":26,"weight":11,"size":"Large","stats":{"sta":5,"agi":4},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-boots-silver","slots":["Feet"],"ac":13,"weight":7.5,"size":"Medium","stats":{"sta":4,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-bracers-silver","slots":["Wrist"],"ac":12,"weight":4.4,"size":"Small","stats":{"sta":3,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-collar-silver","slots":["Neck"],"ac":9,"weight":4.5,"size":"Small","stats":{"sta":3,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-gauntlets-silver","slots":["Hands"],"ac":14,"weight":5.5,"size":"Small","stats":{"sta":4,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-girdle-silver","slots":["Waist"],"ac":10,"weight":4.5,"size":"Small","stats":{"sta":3,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-greaves-silver","slots":["Legs"],"ac":18,"weight":8.5,"size":"Large","stats":{"sta":5,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-helm-silver","slots":["Head"],"ac":15,"weight":5,"size":"Small","stats":{"sta":4,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-pauldron-silver","slots":["Shoulders"],"ac":13,"weight":5,"size":"Small","stats":{"sta":3,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-vambraces-silver","slots":["Arms"],"ac":14,"weight":7,"size":"Small","stats":{"sta":4,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-visor-silver","slots":["Face"],"ac":7,"weight":2,"size":"Small","stats":{"sta":3,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-splinted-cloak-silver","slots":["Back"],"ac":14,"weight":6.5,"size":"Large","stats":{"sta":5,"agi":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-breastplate-electrum","slots":["Chest"],"ac":26,"weight":11,"size":"Large","stats":{"dex":5},"resists":{"magic":5},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-boots-electrum","slots":["Feet"],"ac":13,"weight":7.5,"size":"Small","stats":{"dex":4},"resists":{"magic":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-bracers-electrum","slots":["Wrist"],"ac":12,"weight":4.4,"size":"Small","stats":{"dex":3},"resists":{"magic":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-collar-electrum","slots":["Neck"],"ac":9,"weight":4.5,"size":"Small","stats":{"dex":3},"resists":{"magic":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-gauntlets-electrum","slots":["Hands"],"ac":14,"weight":5.5,"size":"Small","stats":{"dex":4},"resists":{"magic":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-girdle-electrum","slots":["Waist"],"ac":10,"weight":4.5,"size":"Small","stats":{"dex":3},"resists":{"magic":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-greaves-electrum","slots":["Legs"],"ac":18,"weight":8.5,"size":"Large","stats":{"dex":4},"resists":{"magic":4},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-helm-electrum","slots":["Head"],"ac":15,"weight":5,"size":"Small","stats":{"dex":3},"resists":{"magic":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-pauldron-electrum","slots":["Shoulders"],"ac":13,"weight":5,"size":"Small","stats":{"dex":3},"resists":{"magic":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-vambraces-electrum","slots":["Arms"],"ac":14,"weight":7,"size":"Small","stats":{"dex":3},"resists":{"magic":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-visor-electrum","slots":["Face"],"ac":7,"weight":2,"size":"Small","stats":{"dex":3},"resists":{"magic":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-splinted-cloak-electrum","slots":["Back"],"ac":14,"weight":6.5,"size":"Large","stats":{"dex":4},"resists":{"magic":4},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-breastplate-gold","slots":["Chest"],"ac":26,"weight":11,"size":"Large","stats":{"wis":5,"cha":5},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-boots-gold","slots":["Feet"],"ac":13,"weight":7.5,"size":"Medium","stats":{"wis":2,"cha":4},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-bracers-gold","slots":["Wrist"],"ac":12,"weight":4.4,"size":"Small","stats":{"wis":2,"cha":2},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-collar-gold","slots":["Neck"],"ac":9,"weight":4.5,"size":"Small","stats":{"wis":2,"cha":2},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-gauntlets-gold","slots":["Hands"],"ac":14,"weight":5.5,"size":"Small","stats":{"wis":2,"cha":4},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-girdle-gold","slots":["Waist"],"ac":10,"weight":4.5,"size":"Small","stats":{"wis":3,"cha":3},"resists":{"disease":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-greaves-gold","slots":["Legs"],"ac":18,"weight":8.5,"size":"Large","stats":{"wis":2,"cha":4},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-helm-gold","slots":["Head"],"ac":15,"weight":5,"size":"Small","stats":{"wis":3,"cha":4},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-pauldron-gold","slots":["Shoulders"],"ac":13,"weight":5,"size":"Small","stats":{"wis":3,"cha":3},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-vambraces-gold","slots":["Arms"],"ac":14,"weight":7,"size":"Small","stats":{"wis":2,"cha":4},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-visor-gold","slots":["Face"],"ac":7,"weight":2,"size":"Small","stats":{"wis":2,"cha":2},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-splinted-cloak-gold","slots":["Back"],"ac":14,"weight":6.5,"size":"Large","stats":{"wis":4,"cha":4},"resists":{"disease":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-breastplate-platinum","slots":["Chest"],"ac":26,"weight":11,"size":"Large","stats":{"str":5,"int":5},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-boots-platinum","slots":["Feet"],"ac":13,"weight":7.5,"size":"Medium","stats":{"str":2,"int":4},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-bracers-platinum","slots":["Wrist"],"ac":12,"weight":4.4,"size":"Small","stats":{"str":2,"int":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-collar-platinum","slots":["Neck"],"ac":9,"weight":4.5,"size":"Small","stats":{"str":2,"int":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-gauntlets-platinum","slots":["Hands"],"ac":14,"weight":5.5,"size":"Small","stats":{"str":2,"int":4},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-girdle-platinum","slots":["Waist"],"ac":10,"weight":4.5,"size":"Small","stats":{"str":2,"int":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-greaves-platinum","slots":["Legs"],"ac":18,"weight":8.5,"size":"Large","stats":{"str":2,"int":4},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-helm-platinum","slots":["Head"],"ac":15,"weight":5,"size":"Small","stats":{"str":3,"int":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-pauldron-platinum","slots":["Shoulders"],"ac":13,"weight":5,"size":"Small","stats":{"str":3,"int":3},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-vambraces-platinum","slots":["Arms"],"ac":14,"weight":7,"size":"Small","stats":{"str":2,"int":4},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-plate-visor-platinum","slots":["Face"],"ac":7,"weight":2,"size":"Small","stats":{"str":2,"int":2},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:enchanted-full-splinted-cloak-platinum","slots":["Back"],"ac":14,"weight":6.5,"size":"Large","stats":{"str":3,"int":4},"magic":true,"classes":["cleric","paladin","shadow knight","warrior","bard"]},
  {"id":"item:imbued-field-breastplate-bertoxxulous","slots":["Chest"],"ac":24,"weight":10.5,"size":"Large","stats":{"str":2,"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-pauldron-bertoxxulous","slots":["Shoulders"],"ac":11,"weight":4.8,"size":"Small","stats":{"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-vambraces-bertoxxulous","slots":["Arms"],"ac":13,"weight":6.8,"size":"Small","stats":{"str":2,"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-visor-bertoxxulous","slots":["Face"],"ac":6,"weight":1.7,"size":"Small","stats":{"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-helm-bertoxxulous","slots":["Head"],"ac":13,"weight":4.8,"size":"Small","stats":{"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-greaves-bertoxxulous","slots":["Legs"],"ac":16,"weight":8,"size":"Large","stats":{"str":2,"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-girdle-bertoxxulous","slots":["Waist"],"ac":9,"weight":4.2,"size":"Small","stats":{"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-gauntlets-bertoxxulous","slots":["Hands"],"ac":12,"weight":5.2,"size":"Small","stats":{"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-collar-bertoxxulous","slots":["Neck"],"ac":8,"weight":4.2,"size":"Small","stats":{"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-cloak-bertoxxulous","slots":["Back"],"ac":12,"weight":6,"size":"Large","stats":{"str":2,"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-bracers-bertoxxulous","slots":["Wrist"],"ac":10,"weight":4.2,"size":"Small","stats":{"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-boots-bertoxxulous","slots":["Feet"],"ac":12,"weight":7,"size":"Medium","stats":{"wis":2,"int":4,"cha":-2},"resists":{"disease":2},"deity":"Bertoxxulous","classes":["cleric","paladin","shadow knight","warrior"]},
  {"id":"item:imbued-field-breastplate-erollisi-marr","slots":["Chest"],"ac":24,"weight":10.5,"size":"Large","stats":{"str":2,"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-pauldron-erollisi-marr","slots":["Shoulders"],"ac":11,"weight":4.8,"size":"Small","stats":{"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-vambraces-erollisi-marr","slots":["Arms"],"ac":13,"weight":6.8,"size":"Small","stats":{"str":2,"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-visor-erollisi-marr","slots":["Face"],"ac":6,"weight":1.7,"size":"Small","stats":{"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-helm-erollisi-marr","slots":["Head"],"ac":13,"weight":4.8,"size":"Small","stats":{"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-greaves-erollisi-marr","slots":["Legs"],"ac":16,"weight":8,"size":"Large","stats":{"str":2,"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-girdle-erollisi-marr","slots":["Waist"],"ac":9,"weight":4.2,"size":"Small","stats":{"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-gauntlets-erollisi-marr","slots":["Hands"],"ac":12,"weight":5.2,"size":"Small","stats":{"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-collar-erollisi-marr","slots":["Neck"],"ac":8,"weight":4.2,"size":"Small","stats":{"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-cloak-erollisi-marr","slots":["Back"],"ac":12,"weight":6,"size":"Large","stats":{"str":2,"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-bracers-erollisi-marr","slots":["Wrist"],"ac":10,"weight":4.2,"size":"Small","stats":{"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-boots-erollisi-marr","slots":["Feet"],"ac":12,"weight":7,"size":"Medium","stats":{"wis":4,"cha":2},"deity":"Erollisi Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-breastplate-innoruuk","slots":["Chest"],"ac":24,"weight":10.5,"size":"Large","stats":{"str":2,"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-pauldron-innoruuk","slots":["Shoulders"],"ac":11,"weight":4.8,"size":"Small","stats":{"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-vambraces-innoruuk","slots":["Arms"],"ac":13,"weight":6.8,"size":"Small","stats":{"str":2,"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-visor-innoruuk","slots":["Face"],"ac":6,"weight":1.7,"size":"Small","stats":{"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-helm-innoruuk","slots":["Head"],"ac":13,"weight":4.8,"size":"Small","stats":{"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-greaves-innoruuk","slots":["Legs"],"ac":16,"weight":8,"size":"Large","stats":{"str":2,"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-girdle-innoruuk","slots":["Waist"],"ac":9,"weight":4.2,"size":"Small","stats":{"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-gauntlets-innoruuk","slots":["Hands"],"ac":12,"weight":5.2,"size":"Small","stats":{"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-collar-innoruuk","slots":["Neck"],"ac":8,"weight":4.2,"size":"Small","stats":{"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-cloak-innoruuk","slots":["Back"],"ac":12,"weight":6,"size":"Large","stats":{"str":2,"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-bracers-innoruuk","slots":["Wrist"],"ac":10,"weight":4.2,"size":"Small","stats":{"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-plate-boots-innoruuk","slots":["Feet"],"ac":12,"weight":7,"size":"Medium","stats":{"wis":2,"int":4},"deity":"Innoruuk","classes":["cleric","shadow knight","warrior"]},
  {"id":"item:imbued-field-breastplate-karana","slots":["Chest"],"ac":24,"weight":10.5,"size":"Large","stats":{"sta":2,"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-pauldron-karana","slots":["Shoulders"],"ac":11,"weight":4.8,"size":"Small","stats":{"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-vambraces-karana","slots":["Arms"],"ac":13,"weight":6.8,"size":"Small","stats":{"sta":2,"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-visor-karana","slots":["Face"],"ac":6,"weight":1.7,"size":"Small","stats":{"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-helm-karana","slots":["Head"],"ac":13,"weight":4.8,"size":"Small","stats":{"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-greaves-karana","slots":["Legs"],"ac":16,"weight":8,"size":"Large","stats":{"sta":2,"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-girdle-karana","slots":["Waist"],"ac":9,"weight":4.2,"size":"Small","stats":{"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-gauntlets-karana","slots":["Hands"],"ac":12,"weight":5.2,"size":"Small","stats":{"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-collar-karana","slots":["Neck"],"ac":8,"weight":4.2,"size":"Small","stats":{"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-cloak-karana","slots":["Back"],"ac":12,"weight":6,"size":"Large","stats":{"sta":2,"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-bracers-karana","slots":["Wrist"],"ac":10,"weight":4.2,"size":"Small","stats":{"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-boots-karana","slots":["Feet"],"ac":12,"weight":7,"size":"Medium","stats":{"dex":2,"wis":4},"deity":"Karana","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-breastplate-mithaniel-marr","slots":["Chest"],"ac":24,"weight":10.5,"size":"Large","stats":{"str":4,"wis":2,"cha":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-pauldron-mithaniel-marr","slots":["Shoulders"],"ac":11,"weight":4.8,"size":"Small","stats":{"str":4,"wis":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-vambraces-mithaniel-marr","slots":["Arms"],"ac":13,"weight":6.8,"size":"Small","stats":{"str":4,"wis":2,"cha":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-visor-mithaniel-marr","slots":["Face"],"ac":6,"weight":1.7,"size":"Small","stats":{"str":4,"wis":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-helm-mithaniel-marr","slots":["Head"],"ac":13,"weight":4.8,"size":"Small","stats":{"str":4,"wis":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-greaves-mithaniel-marr","slots":["Legs"],"ac":16,"weight":8,"size":"Large","stats":{"str":4,"wis":2,"cha":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-girdle-mithaniel-marr","slots":["Waist"],"ac":9,"weight":4.2,"size":"Small","stats":{"str":4,"wis":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-gauntlets-mithaniel-marr","slots":["Hands"],"ac":12,"weight":5.2,"size":"Small","stats":{"str":4,"wis":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-collar-mithaniel-marr","slots":["Neck"],"ac":8,"weight":4.2,"size":"Small","stats":{"str":4,"wis":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-cloak-mithaniel-marr","slots":["Back"],"ac":12,"weight":6,"size":"Large","stats":{"str":4,"wis":2,"cha":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-bracers-mithaniel-marr","slots":["Wrist"],"ac":10,"weight":4.2,"size":"Small","stats":{"str":4,"wis":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-boots-mithaniel-marr","slots":["Feet"],"ac":12,"weight":7,"size":"Medium","stats":{"str":4,"wis":2},"resists":{"magic":2},"deity":"Mithaniel Marr","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-breastplate-rallos-zek","slots":["Chest"],"ac":24,"weight":10.5,"size":"Large","stats":{"str":6,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-pauldron-rallos-zek","slots":["Shoulders"],"ac":11,"weight":4.8,"size":"Small","stats":{"str":4,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-vambraces-rallos-zek","slots":["Arms"],"ac":13,"weight":6.8,"size":"Small","stats":{"str":6,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-visor-rallos-zek","slots":["Face"],"ac":6,"weight":1.7,"size":"Small","stats":{"str":4,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-helm-rallos-zek","slots":["Head"],"ac":13,"weight":4.8,"size":"Small","stats":{"str":4,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-greaves-rallos-zek","slots":["Legs"],"ac":16,"weight":8,"size":"Large","stats":{"str":6,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-girdle-rallos-zek","slots":["Waist"],"ac":9,"weight":4.2,"size":"Small","stats":{"str":4,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-gauntlets-rallos-zek","slots":["Hands"],"ac":12,"weight":5.2,"size":"Small","stats":{"str":4,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-collar-rallos-zek","slots":["Neck"],"ac":8,"weight":4.2,"size":"Small","stats":{"str":4,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-cloak-rallos-zek","slots":["Back"],"ac":12,"weight":6,"size":"Large","stats":{"str":6,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-bracers-rallos-zek","slots":["Wrist"],"ac":10,"weight":4.2,"size":"Small","stats":{"str":4,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-plate-boots-rallos-zek","slots":["Feet"],"ac":12,"weight":7,"size":"Medium","stats":{"str":4,"sta":2},"deity":"Rallos Zek","classes":["warrior","bard"]},
  {"id":"item:imbued-field-breastplate-rodcet-nife","slots":["Chest"],"ac":24,"weight":10.5,"size":"Large","stats":{"sta":2,"wis":4,"cha":2},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-pauldron-rodcet-nife","slots":["Shoulders"],"ac":11,"weight":4.8,"size":"Small","stats":{"sta":2,"wis":4},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-vambraces-rodcet-nife","slots":["Arms"],"ac":13,"weight":6.8,"size":"Small","stats":{"sta":2,"wis":4,"cha":2},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-visor-rodcet-nife","slots":["Face"],"ac":6,"weight":1.7,"size":"Small","stats":{"sta":2,"wis":4},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-helm-rodcet-nife","slots":["Head"],"ac":13,"weight":4.8,"size":"Small","stats":{"sta":2,"wis":4},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-greaves-rodcet-nife","slots":["Legs"],"ac":16,"weight":8,"size":"Large","stats":{"sta":2,"wis":4,"cha":2},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-girdle-rodcet-nife","slots":["Waist"],"ac":9,"weight":4.2,"size":"Small","stats":{"sta":2,"wis":4},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-gauntlets-rodcet-nife","slots":["Hands"],"ac":12,"weight":5.2,"size":"Small","stats":{"sta":2,"wis":4},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-collar-rodcet-nife","slots":["Neck"],"ac":8,"weight":4.2,"size":"Small","stats":{"sta":2,"wis":4},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-cloak-rodcet-nife","slots":["Back"],"ac":12,"weight":6,"size":"Large","stats":{"sta":2,"wis":4,"cha":2},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-bracers-rodcet-nife","slots":["Wrist"],"ac":10,"weight":4.2,"size":"Small","stats":{"sta":2,"wis":4},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]},
  {"id":"item:imbued-field-plate-boots-rodcet-nife","slots":["Feet"],"ac":12,"weight":7,"size":"Medium","stats":{"sta":2,"wis":4},"deity":"Rodcet Nife","classes":["cleric","paladin","warrior","bard"]}
];

for (const u of updates) {
  const { id, ...fields } = u;
  updateNode(id, fields);
}

save();
console.log(`Updated ${updates.length} items with full stat blocks.`);
