/**
 * Migration 430: model Jewelcrafting's Deity-tier jewelry (issue #50), same
 * `recipe --uses--> item` / `recipe --produces--> item` shape as migrations
 * 425-429 -- see decisions/tradeskill-recipe-node-schema.md.
 *
 * Unlike every earlier tier, eqlwiki's own individual item pages mostly
 * don't have a real trivial value for these 60 recipes -- most literally
 * say "Trivial: ??" (or a bare "?", or a one-sided bound like "<217" /
 * ">= 192"), and the page-level Deity Crafters Item Table is equally sparse.
 * Per the project owner's explicit direction (2026-08-05), trivial is
 * estimated by interpolating each item's own material Cost (also given by
 * the Crafters Item Table) against that same metal's Basic-tier Cost/Trivial
 * curve (migrations 425-428), since Cost and Trivial track tightly within a
 * metal (confirmed: Deity items' Cost values match Basic-tier Cost values
 * almost exactly at matching price points). Validated against the 3 items
 * that DO have a real wiki trivial (Golden Ivory Earring: wiki 183 vs.
 * estimated 186; Jaded Platinum Ring: wiki 250 vs. estimated 250; Platinum
 * Fire Ring: wiki 268 vs. estimated 268) -- close enough to trust the
 * method. The 4 Black Sapphire items (a rare mob-drop gem per the main
 * page's own footnote) have Cost far above any Basic-tier item in their
 * metal; rather than linearly extrapolate into implausible territory (a
 * naive extrapolation put Platinum's estimate at 381, above even Velium
 * tier's own max), their trivial is clamped to that metal's own Basic-tier
 * ceiling. Every recipe's `source` field states its trivial is an estimate,
 * not a wiki-sourced fact, so this is visible in the data itself.
 *
 * Deity restriction comes from the Crafters Item Table's own Deity column
 * (complete for all 60 rows, unlike some individual pages' statsblocks
 * which omit the Deity: line). Class restriction (item-node-schema.md's
 * `classes`) is ALL for every gem except Fire Opal/Solusek Ro, whose 4
 * items are explicitly Bard/Wizard-only per both the main page's own note
 * ("Solusek Ro's Jewelry... only usable by Bards and Wizards") and each
 * item's own "Class: BRD WIZ" statsblock line. No bonus/proc effect beyond
 * the stat block on any of the 60. Same unenchanted-bar-link normalization
 * as migrations 426-429 where relevant.
 *
 * Three imbued gems (Imbued Topaz, Imbued Black Pearl, Imbued Fire Opal)
 * didn't exist yet -- added with the same WT 0.1/Size Tiny/no-vendor shape
 * as the twelve imbued gems already in the graph from earlier work.
 */

import { loadGraph } from "./_lib";

const { hasNode, addNode, addEdge, save } = loadGraph(import.meta.dir);

let recipesAdded = 0;
let itemsAdded = 0;

function addGem(id: string, label: string, source: string) {
  if (hasNode(id)) return;
  addNode({ id, label, type: "item", weight: 0.1, size: "Tiny", source });
  itemsAdded++;
}

addGem("item:imbued-topaz", "Imbued Topaz", "Created from Topaz via the Imbue Topaz spell; deity-restricted to Quellious");
addGem("item:imbued-black-pearl", "Imbued Black Pearl", "Created from Black Pearl via the Imbue Black Pearl spell; deity-restricted to Prexus");
addGem("item:imbued-fire-opal", "Imbued Fire Opal", "Created from Fire Opal via the Imbue Fire Opal spell; deity-restricted to Solusek Ro, Wizard-only to cast");

interface ItemOpts {
  ac?: number;
  hp?: number;
  mana?: number;
  stats?: Record<string, number>;
  resists?: Record<string, number>;
  weight?: number;
  size?: string;
  slots?: string[];
  deity?: string;
  classes?: string[];
  source?: string;
}

function addRecipe(recipeId: string, label: string, trivial: number, gemId: string, barId: string, producedId: string, itemOpts: ItemOpts) {
  addNode({ id: producedId, label, type: "item", ...itemOpts });
  addNode({ id: recipeId, label, type: "recipe", tradeskill: "Jewelcrafting", trivial });
  addEdge(recipeId, barId, "uses");
  addEdge(recipeId, gemId, "uses");
  addEdge(recipeId, producedId, "produces");
  addEdge(recipeId, "container:jewelers-kit", "crafted_in");
  recipesAdded++;
}

addRecipe("recipe:imbued-silver-plains-ring", "Imbued Silver Plains Ring", 49, "item:imbued-plains-pebble", "item:enchanted-silver-bar", "item:imbued-silver-plains-ring", { stats: {"str":-1,"sta":2,"wis":1}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Karana", source: "Estimated trivial 49 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-electrum-plains-earring", "Imbued Electrum Plains Earring", 117, "item:imbued-plains-pebble", "item:enchanted-electrum-bar", "item:imbued-electrum-plains-earring", { stats: {"str":-2,"sta":2,"wis":2}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Karana", source: "Estimated trivial 117 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-plains-earring", "Imbued Golden Plains Earring", 189, "item:imbued-plains-pebble", "item:enchanted-gold-bar", "item:imbued-golden-plains-earring", { stats: {"str":-3,"sta":2,"wis":4}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Karana", source: "Estimated trivial 189 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-plains-ring", "Imbued Platinum Plains Ring", 261, "item:imbued-plains-pebble", "item:enchanted-platinum-bar", "item:imbued-platinum-plains-ring", { stats: {"str":-4,"sta":3,"wis":5}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Karana", source: "Estimated trivial 261 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-ivory-silver-necklace", "Imbued Ivory Silver Necklace", 46, "item:imbued-ivory", "item:enchanted-silver-bar", "item:imbued-ivory-silver-necklace", { ac: 3, stats: {"wis":2}, resists: {"cold":3}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "The Tribunal", source: "Estimated trivial 46 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-ivory-electrum-earring", "Imbued Ivory Electrum Earring", 114, "item:imbued-ivory", "item:enchanted-electrum-bar", "item:imbued-ivory-electrum-earring", { ac: 2, stats: {"wis":1}, resists: {"cold":4}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "The Tribunal", source: "Estimated trivial 114 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-ivory-earring", "Imbued Golden Ivory Earring", 186, "item:imbued-ivory", "item:enchanted-gold-bar", "item:imbued-golden-ivory-earring", { ac: 3, stats: {"wis":4}, resists: {"cold":4}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "The Tribunal", source: "Estimated trivial 186 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-ivory-necklace", "Imbued Platinum Ivory Necklace", 258, "item:imbued-ivory", "item:enchanted-platinum-bar", "item:imbued-platinum-ivory-necklace", { ac: 5, stats: {"wis":5}, resists: {"cold":8}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "The Tribunal", source: "Estimated trivial 258 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-silver-rose-ring", "Imbued Silver Rose Ring", 34, "item:imbued-rose-quartz", "item:enchanted-silver-bar", "item:imbued-silver-rose-ring", { stats: {"sta":-1,"int":1,"wis":2}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Erollisi Marr", source: "Estimated trivial 34 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-electrum-rose-amulet", "Imbued Electrum Rose Amulet", 98, "item:imbued-rose-quartz", "item:enchanted-electrum-bar", "item:imbued-electrum-rose-amulet", { stats: {"sta":-1,"int":1,"wis":2}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Erollisi Marr", source: "Estimated trivial 98 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-rose-amulet", "Imbued Golden Rose Amulet", 170, "item:imbued-rose-quartz", "item:enchanted-gold-bar", "item:imbued-golden-rose-amulet", { stats: {"sta":-2,"int":2,"wis":4}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Erollisi Marr", source: "Estimated trivial 170 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-rose-platinum-ring", "Imbued Rose Platinum Ring", 242, "item:imbued-rose-quartz", "item:enchanted-platinum-bar", "item:imbued-rose-platinum-ring", { stats: {"sta":-2,"int":2,"wis":4}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Erollisi Marr", source: "Estimated trivial 242 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-silver-amber-ring", "Imbued Silver Amber Ring", 36, "item:imbued-amber", "item:enchanted-silver-bar", "item:imbued-silver-amber-ring", { stats: {"str":2,"int":1,"cha":-1}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Cazic-Thule", source: "Estimated trivial 36 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-electrum-amber-earring", "Imbued Electrum Amber Earring", 100, "item:imbued-amber", "item:enchanted-electrum-bar", "item:imbued-electrum-amber-earring", { stats: {"str":1,"int":2,"cha":-2}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Cazic-Thule", source: "Estimated trivial 100 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-amber-earring", "Imbued Golden Amber Earring", 172, "item:imbued-amber", "item:enchanted-gold-bar", "item:imbued-golden-amber-earring", { stats: {"str":3,"int":3,"cha":-3}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Cazic-Thule", source: "Estimated trivial 172 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-amber-ring", "Imbued Platinum Amber Ring", 244, "item:imbued-amber", "item:enchanted-platinum-bar", "item:imbued-platinum-amber-ring", { stats: {"str":4,"int":4,"cha":-4}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Cazic-Thule", source: "Estimated trivial 244 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-jaded-silver-ring", "Imbued Jaded Silver Ring", 40, "item:imbued-jade", "item:enchanted-silver-bar", "item:imbued-jaded-silver-ring", { ac: 1, hp: 10, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Rallos Zek", source: "Estimated trivial 40 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-jaded-electrum-bracelet", "Imbued Jaded Electrum Bracelet", 106, "item:imbued-jade", "item:enchanted-electrum-bar", "item:imbued-jaded-electrum-bracelet", { ac: 2, hp: 20, weight: 0.1, size: "Tiny", slots: ["Wrist"], deity: "Rallos Zek", source: "Estimated trivial 106 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-jaded-bracelet", "Imbued Golden Jaded Bracelet", 178, "item:imbued-jade", "item:enchanted-gold-bar", "item:imbued-golden-jaded-bracelet", { ac: 2, hp: 30, weight: 0.1, size: "Tiny", slots: ["Wrist"], deity: "Rallos Zek", source: "Estimated trivial 178 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-jaded-platinum-ring", "Imbued Jaded Platinum Ring", 250, "item:imbued-jade", "item:enchanted-platinum-bar", "item:imbued-jaded-platinum-ring", { ac: 4, hp: 40, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Rallos Zek", source: "Estimated trivial 250 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-topaz-silver-necklace", "Imbued Topaz Silver Necklace", 44, "item:imbued-topaz", "item:enchanted-silver-bar", "item:imbued-topaz-silver-necklace", { ac: 3, stats: {"cha":2}, resists: {"disease":3}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Quellious", source: "Estimated trivial 44 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-topaz-electrum-earring", "Imbued Topaz Electrum Earring", 111, "item:imbued-topaz", "item:enchanted-electrum-bar", "item:imbued-topaz-electrum-earring", { ac: 2, stats: {"cha":1}, resists: {"disease":4}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Quellious", source: "Estimated trivial 111 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-topaz-earring", "Imbued Golden Topaz Earring", 183, "item:imbued-topaz", "item:enchanted-gold-bar", "item:imbued-golden-topaz-earring", { ac: 3, stats: {"cha":4}, resists: {"disease":4}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Quellious", source: "Estimated trivial 183 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-topaz-necklace", "Imbued Platinum Topaz Necklace", 255, "item:imbued-topaz", "item:enchanted-platinum-bar", "item:imbued-platinum-topaz-necklace", { ac: 5, stats: {"cha":5}, resists: {"disease":8}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Quellious", source: "Estimated trivial 255 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-silvered-peridot-ring", "Imbued Silvered Peridot Ring", 46, "item:imbued-peridot", "item:enchanted-silver-bar", "item:imbued-silvered-peridot-ring", { ac: 1, stats: {"agi":3}, resists: {"cold":3}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Bristlebane", source: "Estimated trivial 46 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-electrum-peridot-bracelet", "Imbued Electrum Peridot Bracelet", 114, "item:imbued-peridot", "item:enchanted-electrum-bar", "item:imbued-electrum-peridot-bracelet", { ac: 2, stats: {"agi":3}, resists: {"cold":2}, weight: 0.1, size: "Tiny", slots: ["Wrist"], deity: "Bristlebane", source: "Estimated trivial 114 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-peridot-bracelet", "Imbued Golden Peridot Bracelet", 186, "item:imbued-peridot", "item:enchanted-gold-bar", "item:imbued-golden-peridot-bracelet", { ac: 3, stats: {"agi":4}, resists: {"cold":3}, weight: 0.1, size: "Tiny", slots: ["Wrist"], deity: "Bristlebane", source: "Estimated trivial 186 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-peridot-ring", "Imbued Platinum Peridot Ring", 258, "item:imbued-peridot", "item:enchanted-platinum-bar", "item:imbued-platinum-peridot-ring", { ac: 3, stats: {"agi":6}, resists: {"cold":5}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Bristlebane", source: "Estimated trivial 258 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-silver-emerald-ring", "Imbued Silver Emerald Ring", 48, "item:imbued-emerald", "item:enchanted-silver-bar", "item:imbued-silver-emerald-ring", { ac: 2, stats: {"str":-1,"dex":1}, resists: {"fire":3,"disease":2}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Tunare", source: "Estimated trivial 48 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-emerald-electrum-bracelet", "Imbued Emerald Electrum Bracelet", 116, "item:imbued-emerald", "item:enchanted-electrum-bar", "item:imbued-emerald-electrum-bracelet", { ac: 3, stats: {"str":-2,"dex":2}, resists: {"fire":2,"disease":2}, weight: 0.1, size: "Tiny", slots: ["Wrist"], deity: "Tunare", source: "Estimated trivial 116 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-emerald-bracelet", "Imbued Golden Emerald Bracelet", 188, "item:imbued-emerald", "item:enchanted-gold-bar", "item:imbued-golden-emerald-bracelet", { ac: 4, stats: {"str":-3,"dex":3}, resists: {"fire":4,"disease":2}, weight: 0.1, size: "Tiny", slots: ["Wrist"], deity: "Tunare", source: "Estimated trivial 188 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-emerald-ring", "Imbued Platinum Emerald Ring", 260, "item:imbued-emerald", "item:enchanted-platinum-bar", "item:imbued-platinum-emerald-ring", { ac: 4, stats: {"str":-4,"dex":4}, resists: {"fire":8,"disease":2}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Tunare", source: "Estimated trivial 260 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-silver-opal-ring", "Imbued Silver Opal Ring", 50, "item:imbued-opal", "item:enchanted-silver-bar", "item:imbued-silver-opal-ring", { stats: {"sta":2,"agi":1}, resists: {"disease":2,"poison":2}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Rodcet Nife", source: "Estimated trivial 50 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-electrum-opal-amulet", "Imbued Electrum Opal Amulet", 119, "item:imbued-opal", "item:enchanted-electrum-bar", "item:imbued-electrum-opal-amulet", { stats: {"sta":3,"agi":2}, resists: {"disease":2,"poison":2}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Rodcet Nife", source: "Estimated trivial 119 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-opal-amulet", "Imbued Golden Opal Amulet", 191, "item:imbued-opal", "item:enchanted-gold-bar", "item:imbued-golden-opal-amulet", { stats: {"sta":7,"agi":4}, resists: {"disease":4,"poison":4}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Rodcet Nife", source: "Estimated trivial 191 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-opal-ring", "Imbued Platinum Opal Ring", 263, "item:imbued-opal", "item:enchanted-platinum-bar", "item:imbued-platinum-opal-ring", { stats: {"sta":6,"agi":4}, resists: {"disease":2,"poison":2}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Rodcet Nife", source: "Estimated trivial 263 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-blackened-pearl-silver-ring", "Imbued Blackened Pearl Silver Ring", 52, "item:imbued-black-pearl", "item:enchanted-silver-bar", "item:imbued-blackened-pearl-silver-ring", { stats: {"dex":2,"agi":2,"wis":2}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Prexus", source: "Estimated trivial 52 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-black-pearl-electrum-choker", "Imbued Black Pearl Electrum Choker", 122, "item:imbued-black-pearl", "item:enchanted-electrum-bar", "item:imbued-black-pearl-electrum-choker", { stats: {"dex":3,"agi":3,"wis":2}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Prexus", source: "Estimated trivial 122 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-black-pearl-choker", "Imbued Golden Black Pearl Choker", 194, "item:imbued-black-pearl", "item:enchanted-gold-bar", "item:imbued-golden-black-pearl-choker", { stats: {"dex":5,"agi":5,"wis":4}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Prexus", source: "Estimated trivial 194 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-black-pearl-platinum-ring", "Imbued Black Pearl Platinum Ring", 266, "item:imbued-black-pearl", "item:enchanted-platinum-bar", "item:imbued-black-pearl-platinum-ring", { stats: {"dex":5,"agi":5,"wis":5}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Prexus", source: "Estimated trivial 266 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-silver-fire-ring", "Imbued Silver Fire Ring", 54, "item:imbued-fire-opal", "item:enchanted-silver-bar", "item:imbued-silver-fire-ring", { ac: 1, hp: 10, mana: 20, stats: {"str":-2,"int":2}, resists: {"fire":1}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Solusek Ro", classes: ["Bard","Wizard"], source: "Estimated trivial 54 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-electrum-fire-ring", "Imbued Electrum Fire Ring", 124, "item:imbued-fire-opal", "item:enchanted-electrum-bar", "item:imbued-electrum-fire-ring", { ac: 2, hp: 10, mana: 25, stats: {"str":-4,"int":4}, resists: {"fire":2}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Solusek Ro", classes: ["Bard","Wizard"], source: "Estimated trivial 124 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-fire-ring", "Imbued Golden Fire Ring", 196, "item:imbued-fire-opal", "item:enchanted-gold-bar", "item:imbued-golden-fire-ring", { ac: 3, hp: 10, mana: 35, stats: {"str":-6,"int":6}, resists: {"fire":3}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Solusek Ro", classes: ["Bard","Wizard"], source: "Estimated trivial 196 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-fire-ring", "Imbued Platinum Fire Ring", 268, "item:imbued-fire-opal", "item:enchanted-platinum-bar", "item:imbued-platinum-fire-ring", { ac: 4, hp: 10, mana: 45, stats: {"str":-8,"int":8}, resists: {"fire":4}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Solusek Ro", classes: ["Bard","Wizard"], source: "Estimated trivial 268 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-silvered-sapphire-necklace", "Imbued Silvered Sapphire Necklace", 60, "item:imbued-sapphire", "item:enchanted-silver-bar", "item:imbued-silvered-sapphire-necklace", { stats: {"str":3,"dex":2,"int":3}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Innoruuk", source: "Estimated trivial 60 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-sapphire-electrum-earring", "Imbued Sapphire Electrum Earring", 132, "item:imbued-sapphire", "item:enchanted-electrum-bar", "item:imbued-sapphire-electrum-earring", { stats: {"str":3,"dex":1,"int":2}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Innoruuk", source: "Estimated trivial 132 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-sapphire-earring", "Imbued Golden Sapphire Earring", 204, "item:imbued-sapphire", "item:enchanted-gold-bar", "item:imbued-golden-sapphire-earring", { stats: {"str":2,"dex":2,"int":2}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Innoruuk", source: "Estimated trivial 204 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-sapphire-platinum-necklace", "Imbued Sapphire Platinum Necklace", 276, "item:imbued-sapphire", "item:enchanted-platinum-bar", "item:imbued-sapphire-platinum-necklace", { stats: {"str":6,"dex":2,"int":6}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Innoruuk", source: "Estimated trivial 276 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-silver-ruby-veil", "Imbued Silver Ruby Veil", 63, "item:imbued-ruby", "item:enchanted-silver-bar", "item:imbued-silver-ruby-veil", { stats: {"str":4,"sta":1,"agi":-1,"wis":4}, weight: 0.1, size: "Tiny", slots: ["Face"], deity: "Brell Serilis", source: "Estimated trivial 63 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-ruby-electrum-ring", "Imbued Ruby Electrum Ring", 135, "item:imbued-ruby", "item:enchanted-electrum-bar", "item:imbued-ruby-electrum-ring", { stats: {"str":4,"sta":2,"agi":-2,"wis":2}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Brell Serilis", source: "Estimated trivial 135 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-ruby-ring", "Imbued Golden Ruby Ring", 207, "item:imbued-ruby", "item:enchanted-gold-bar", "item:imbued-golden-ruby-ring", { stats: {"str":2,"sta":3,"agi":-3,"wis":4}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Brell Serilis", source: "Estimated trivial 207 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-ruby-veil", "Imbued Platinum Ruby Veil", 279, "item:imbued-ruby", "item:enchanted-platinum-bar", "item:imbued-platinum-ruby-veil", { stats: {"str":7,"sta":4,"agi":-4,"wis":7}, weight: 0.1, size: "Tiny", slots: ["Face"], deity: "Brell Serilis", source: "Estimated trivial 279 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-black-sapphire-silvered-necklace", "Imbued Black Sapphire Silvered Necklace", 75, "item:imbued-black-sapphire", "item:enchanted-silver-bar", "item:imbued-black-sapphire-silvered-necklace", { hp: 20, mana: 40, resists: {"disease":3}, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Bertoxxulous", source: "Estimated trivial 75 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-black-sapphire-electrum-earring", "Imbued Black Sapphire Electrum Earring", 148, "item:imbued-black-sapphire", "item:enchanted-electrum-bar", "item:imbued-black-sapphire-electrum-earring", { hp: 15, mana: 40, resists: {"disease":2}, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Bertoxxulous", source: "Estimated trivial 148 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-black-sapphire-earring", "Imbued Golden Black Sapphire Earring", 228, "item:imbued-black-sapphire", "item:enchanted-gold-bar", "item:imbued-golden-black-sapphire-earring", { hp: 20, mana: 40, weight: 0.1, size: "Tiny", slots: ["Ear"], deity: "Bertoxxulous", source: "Estimated trivial 228 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-black-sapphire-platinum-necklace", "Imbued Black Sapphire Platinum Necklace", 295, "item:imbued-black-sapphire", "item:enchanted-platinum-bar", "item:imbued-black-sapphire-platinum-necklace", { hp: 35, mana: 75, weight: 0.1, size: "Tiny", slots: ["Neck"], deity: "Bertoxxulous", source: "Estimated trivial 295 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-silver-diamond-ring", "Imbued Silver Diamond Ring", 71, "item:imbued-diamond", "item:enchanted-silver-bar", "item:imbued-silver-diamond-ring", { stats: {"sta":2,"wis":3}, resists: {"fire":2,"cold":2,"disease":2,"poison":2,"magic":2}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Mithaniel Marr", source: "Estimated trivial 71 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-diamond-electrum-mask", "Imbued Diamond Electrum Mask", 143, "item:imbued-diamond", "item:enchanted-electrum-bar", "item:imbued-diamond-electrum-mask", { stats: {"sta":4,"wis":4}, resists: {"fire":4,"cold":4,"disease":7,"poison":7,"magic":3}, weight: 0.1, size: "Tiny", slots: ["Face"], deity: "Mithaniel Marr", source: "Estimated trivial 143 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-golden-diamond-mask", "Imbued Golden Diamond Mask", 215, "item:imbued-diamond", "item:enchanted-gold-bar", "item:imbued-golden-diamond-mask", { stats: {"sta":4,"wis":4}, resists: {"fire":7,"cold":7,"disease":4,"poison":4,"magic":3}, weight: 0.1, size: "Tiny", slots: ["Face"], deity: "Mithaniel Marr", source: "Estimated trivial 215 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });
addRecipe("recipe:imbued-platinum-diamond-ring", "Imbued Platinum Diamond Ring", 287, "item:imbued-diamond", "item:enchanted-platinum-bar", "item:imbued-platinum-diamond-ring", { stats: {"sta":5,"wis":5}, resists: {"fire":5,"cold":5,"disease":5,"poison":5,"magic":5}, weight: 0.1, size: "Tiny", slots: ["Finger"], deity: "Mithaniel Marr", source: "Estimated trivial 287 (interpolated from material cost -- eqlwiki's own page gives no reliable value for this item)" });

save();
console.log(`Migration 430 complete: ${recipesAdded} recipe(s), ${itemsAdded} new gem item(s) added for Jewelcrafting (Deity tier)`);
