/**
 * Packs the individual per-icon PNGs downloaded by
 * scripts/extract-spell-icons.ts (public/icons/gem-<key>.png) into one
 * combined sprite sheet (public/icons/spell-icons.png) plus a manifest
 * (public/components/icon-sheet-manifest.js, a plain JS module exporting
 * pixel offsets) so the frontend loads one small image instead of ~120
 * separate ones. Deletes the individual gem-<key>.png files once packed —
 * they're a build-time intermediate, not something the app reads directly.
 *
 * Usage: bun run scripts/build-icon-sheet.ts
 * (run after extract-spell-icons.ts; safe to re-run any time the icon set
 * changes)
 */

import { readdirSync, readFileSync, writeFileSync, unlinkSync } from "fs";
import { resolve } from "path";
import { PNG } from "pngjs";

const ICONS_DIR = resolve(import.meta.dir, "../public/icons");
const SHEET_PATH = resolve(ICONS_DIR, "spell-icons.png");
const MANIFEST_PATH = resolve(import.meta.dir, "../public/components/icon-sheet-manifest.js");
const CELL_SIZE = 40;

const files = readdirSync(ICONS_DIR).filter((f) => /^gem-.+\.png$/.test(f));
const keys = files.map((f) => f.slice("gem-".length, -".png".length)).sort();

const cols = Math.ceil(Math.sqrt(keys.length));
const rows = Math.ceil(keys.length / cols);
const sheet = new PNG({ width: cols * CELL_SIZE, height: rows * CELL_SIZE });

const manifest: Record<string, { x: number; y: number }> = {};

keys.forEach((key, i) => {
  const col = i % cols;
  const row = Math.floor(i / cols);
  const x = col * CELL_SIZE;
  const y = row * CELL_SIZE;
  manifest[key] = { x, y };

  const icon = PNG.sync.read(readFileSync(resolve(ICONS_DIR, `gem-${key}.png`)));
  PNG.bitblt(icon, sheet, 0, 0, CELL_SIZE, CELL_SIZE, x, y);
});

writeFileSync(SHEET_PATH, PNG.sync.write(sheet));
writeFileSync(
  MANIFEST_PATH,
  `// Generated by scripts/build-icon-sheet.ts — pixel offset of each spell\n` +
    `// icon key within public/icons/spell-icons.png (a ${cols}x${rows} grid of\n` +
    `// ${CELL_SIZE}x${CELL_SIZE} cells). Regenerate by re-running that script, not by hand.\n` +
    `export const ICON_SHEET_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n` +
    `export const ICON_CELL_SIZE = ${CELL_SIZE};\n`
);

for (const f of files) unlinkSync(resolve(ICONS_DIR, f));

console.log(`Packed ${keys.length} icons into a ${cols}x${rows} sheet (${sheet.width}x${sheet.height}px) -> public/icons/spell-icons.png`);
console.log(`Manifest written to public/components/icon-sheet-manifest.js`);
console.log(`${files.length} individual gem-*.png files removed.`);
